{
    pools {
        ammId
        name
        version
        serumProgramId
        coin {
            chainId
            address
            name
            decimals
            symbol
            logoURI
        }
        pc {
            chainId
            address
            name
            decimals
            symbol
            logoURI
        }
        lp {
            chainId
            address
            name
            decimals
            symbol
            logoURI
        }
        stats {
            tvl_usd
            price
            vol24h_usd
        }
    }
}