query pool_detail($address: String!) {
  pool(address: $address) {
    ammId
    name
    version
    coin {
      address
      name
      decimals
      symbol
      logoURI
    }
    pc {
      address
      name
      decimals
      symbol
      logoURI
    }
    lp {
      address
      name
      decimals
      symbol
    }
    stats {
      vol24h
      vol7d
      price
      tvl_coin
      tvl_pc
      tvl_usd
    }
  }

  pool_hourly_data(address: $address) {
    time
    price
    tvl_coin
    tvl_pc
    tvl_usd
    volume
  }
}