query pool_detail($address: String!) {
  pool(address: $address) {
    ammId
    name
    version
    coin {
      address
      name
      decimals
      symbol
      logoURI
    }
    pc {
      address
      name
      decimals
      symbol
      logoURI
    }
    lp {
      address
      name
      decimals
      symbol
    }
    stats {
      vol24h
      vol7d
      price
      tvl_coin
      tvl_pc
      tvl_usd
    }
  }

  events(address: $address, limit: 100, max_scan:25000) {
    signature
    blockTime
    type
    meta {
      pool {
        name
        coin {
          symbol
          decimals
        }
        pc {
          symbol
          decimals
        }
      }
      source_amount
      source_token {
        symbol
        decimals
      }
      target_amount
      target_token {
        symbol
        decimals
      }
      coin_amount
      pc_amount
      lp_amount
      usd_value
      direction
      owner
    }
  }

  pool_hourly_data(address: $address) {
    time
    price
    tvl_coin
    tvl_pc
    tvl_usd
    volume
  }
}